#!/bin/bash
# Copyright (C) 2016  graypawn <choi.pawn@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
export DISPLAY=:0
VERSION=1.6.0
ICON=system-software-update

function version_info() {
    echo "Yusuke v$version"
    echo "Copyrig ht (C) 2016 graypawn <choi.pawn@gmail.com>"
    echo "GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>."
    echo "This is free software: you are free to change and redistribute it."
    echo "There is NO WARRANTY, to the extent permitted by law."
}

function usage_info() {
    echo "Usage: yusuke [OPTION]"
}

function help_info() {
    usage_info
    echo "pacman update notifier"
    echo ""
    echo "    --help      display this help and exit"
    echo "    --version   output version information and exit"
}

if [ -n "$1" ]; then
    case $1 in
        "--help")
            help_info
            exit 0 ;;
        "--version")
            version_info
            exit 0 ;;
        *)
            usage_info >&2
            exit 1 ;;
    esac
fi

update_pkg=`pacman -Qu`
pkg_num=`pacman -Qu | wc -l`
if [ $pkg_num != 0 ]; then
    notify-send "$pkg_num Update(s) Available" "$update_pkg" -i $ICON
fi
