#!/usr/bin/env python
# Copyright (C) 2016  graypawn <choi.pawn @gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
import sys
import os
import subprocess
import gi
gi.require_version('Notify', '0.7')
gi.require_version('Gtk', '3.0')
from gi.repository import Notify
from gi.repository import Gtk


ICON = 'system-software-update'
VERSION = '1.7.2'
cache_dir = os.path.expanduser('~')+'/.cache/yusuke'


def versionInfo():
    print("Yusuke", VERSION)
    print("Copyrig ht (C) 2016 graypawn <choi.pawn @gmail.com>")
    print("GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.")
    print("This is free software: you are free to change and redistribute it.")
    print("There is NO WARRANTY, to the extent permitted by law.")


def helpInfo(name):
    print("Usage: {} [OPTION]".format(name))
    print("pacman update notifier")
    print()
    print("    --help      display this help and exit")
    print("    --version   output version information and exit")
    print()
    print("yusuke@.timer checks periodically for updates.")
    print("    systemctl enable yusuke@{USER}.timer")


def isCheckedPackages(package_binary):
    try:
        cache = open(cache_dir + '/cache', 'rb')
        if cache.read() == package_binary:
            return True
        else:
            False
    except (FileNotFoundError, PermissionError):
        return False


def closedCallback(notify_object):
    Gtk.main_quit()


def moreMessageCallback(notify_object, action_name, user_data):
    notify_object.update(
        user_data[0],
        user_data[1],
        ICON
    )
    notify_object.show()


def checkCallback(notify_object, action_name, package_binary):
    try:
        os.makedirs(cache_dir, exist_ok=True)
        with open(cache_dir + '/cache', 'wb') as cache:
            cache.write(package_binary)
    except OSError as e:
        print("yusuke: {}: {}".format(cache_dir + '/cache', e.args[1]))
    notify_object.close()
    Gtk.main_quit()


def main():
    pacman_output = subprocess.check_output(['pacman', '-Qu'])
    if isCheckedPackages(pacman_output):
        return

    update_packages = pacman_output.decode("utf-8")

    # Exclude ignored packages for counting.
    package_num = update_packages.count('\n')-update_packages.count('[ignored]')
    if package_num == 0:
        return

    Notify.init('yusuke')
    title = "{} Update(s) Available".format(package_num)

    # Show only 10 packages.
    if package_num <= 10:
        message = update_packages
    else:
        message = "\n".join(update_packages.split('\n')[0:10])

    yusuke_notify = Notify.Notification.new(title, message, ICON)
    yusuke_notify.connect('closed', closedCallback)

    # Pressing the 'more' button to show full packages.
    yusuke_notify.add_action(
        'more_message',
        'more',
        moreMessageCallback,
        [title, update_packages]
    )
    # If all packages are checked, then don't show this message again.
    yusuke_notify.add_action(
        'no_more',
        "Don't show this message again",
        checkCallback,
        pacman_output
    )
    yusuke_notify.show()
    Gtk.main()


if len(sys.argv) == 1:
    main()
elif sys.argv[1] == '--help':
    helpInfo(sys.argv[0])
    exit(0)
elif sys.argv[1] == '--version':
    versionInfo()
    exit(0)
else:
    print("Try '{} --help' for more information.".format(sys.argv[0]))
    exit(1)
